"""empty message

Revision ID: c299f9fa1a79
Revises: 
Create Date: 2021-03-28 22:51:31.319981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c299f9fa1a79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mymusic_track_id_fkey', 'mymusic', type_='foreignkey')
    op.drop_constraint('mymusic_user_id_fkey', 'mymusic', type_='foreignkey')
    op.create_foreign_key(None, 'mymusic', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'mymusic', 'track', ['track_id'], ['id'])
    op.alter_column('track', 'artist',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('track', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('track', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('track', 'spotify_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'private_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'private_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'spotify_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('track', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('track', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('track', 'artist',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'mymusic', type_='foreignkey')
    op.drop_constraint(None, 'mymusic', type_='foreignkey')
    op.create_foreign_key('mymusic_user_id_fkey', 'mymusic', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('mymusic_track_id_fkey', 'mymusic', 'track', ['track_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
